krzysztof_custom_user:
    resource: "@KrzysztofCustomUserBundle/Resources/config/routing.yml"
    prefix:   /

acme_hello:
    resource: "@AcmeHelloBundle/Resources/config/routing.yml"
    prefix:   /

